version: '3'

services:
  apache:
    build:
      network: host
      dockerfile: php7-apache2.Dockerfile
      context: .
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "USER=${USER}"
    image: ccarvalho/php7-apache2-dockerfile
    container_name: php7-apache2
    restart: always
    ports:
      - '80:80'
    volumes:
      - ${SERVER_DIRECTORY}:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=application

volumes:
    mysqldata: {}